<?php
require_once(__DIR__ . '/../../common/header.phtml');
$action = '/admin/load_from_csv';
?>

<div class="container">
    <form action="<?= $action ?>" method="POST" enctype="multipart/form-data">
        <div class="form-group">
            <label for="csvFile">Choose a csv file</label>
            <input type="file" name="csvFile" class="form-control-file">
        </div>
        <div class="form-group">
            <input type="submit" value="Load" class="btn btn-primary">
        </div>
    </form>
</div>

<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>